name: LaunchDarkly Code References

on:
  push:
    branches: [main]

jobs:
  code-refs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest ld-find-code-refs binary
        run: |
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/launchdarkly/ld-find-code-refs/releases/latest \
            | grep browser_download_url \
            | grep linux-amd64 \
            | cut -d '"' -f 4)
          curl -sSL "$DOWNLOAD_URL" -o ld-find-code-refs
          chmod +x ld-find-code-refs

      - name: Run ld-find-code-refs
        env:
          LD_ACCESS_TOKEN: ${{ secrets.LD_ACCESS_TOKEN }}
        run: |
          ./ld-find-code-refs \
            --proj-key your-project-key \
            --repo-name "${{ github.repository }}" \
            --dir . \
            --ref ${{ github.ref_name }} \
            --access-token "$LD_ACCESS_TOKEN"
