name: LaunchDarkly Code References

on:
  push:
    branches: [main]  # or whichever branch you want to scan from

jobs:
  code-refs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ld-find-code-refs
        run: |
          curl -s https://raw.githubusercontent.com/launchdarkly/ld-find-code-refs/main/scripts/install.sh | bash

      - name: Send code references to LaunchDarkly
        env:
          LD_ACCESS_TOKEN: ${{ secrets.LD_ACCESS_TOKEN }}
        run: |
          ./ld-find-code-refs \
            --proj-key davids-project \
            --repo-name "${{ github.repository }}" \
            --dir . \
            --ref ${{ github.ref_name }} \
            --access-token "$LD_ACCESS_TOKEN"
